### ISSUE TITLE
any reason the image endpoint has not been implemented?

### ISSUE THREAD

**Issue by bodepd** [ruby-openstack/ruby-openstack#24]
I started implementing it, wanted to make sure I'm not duplicating effort. Also, I am a little confused as to how you are handling the versions of APIs for things (are you assuming that an endpoint returns the version to use, are you handling all of the possibilities of each version?)

**Comment by f0086** [comment]
@bodepd Still working on this?

**Comment by bodepd** [comment]
@f0086 no, I don't even remember what I wound up doing it's been so long ago ;)

**Comment by f0086** [comment]
Okay :)
