### ISSUE TITLE
Net::HTTP::Put#body_stream in OpenStack::Connection#put_object does not work correctly with Swift

### ISSUE THREAD

**Issue by allomov** [ruby-openstack/ruby-openstack#44]
I want to upload objects to Swift container. Currently `object.write("penguins have knees")` will return true without update of the object in Swift. The response from Swift API is following: `<Net::HTTPCreated 201 Created readbody=true>`.

My first guess is that this happens because of `Content-Length` is left to be 0 inside [this code](https://github.com/ruby-openstack/ruby-openstack/blob/master/lib/openstack/connection.rb#L120-L124). 

After I passed `String` object to OpenStack::Connection#put_object as a data everything worked.

**Comment by VMMan** [comment]
Is there a way around this issue using Ruby 2.0?

Thanks.

**Comment by CAMOKPYT** [comment]
+1 Really. 1.9 is too old, Why there are no any patches?

**Comment by zhouguangming** [comment]
Who can fix it, please.

**Comment by allomov** [comment]
Unfortunately, I don't have access to a swift store now. Not sure that I will be able to work with it in a close time.

**Comment by alecava** [comment]
Here is a quick and dirty solution to the problem by reopening the ChunkedConnectionWrapper class, I hope it will be helpful

```
module OpenStack
  module Swift
    class ChunkedConnectionWrapper
      def read(length, out_str)
        s = @file.read(length)

        if s.nil?
          return nil
        end

        out_str << s

        s
      end
    end
  end
end
```

**Comment by f0086** [comment]
Fixed in the `next` branch.
