### ISSUE TITLE
ArgumentError: wrong number of arguments (2 for 1) in create_object

### ISSUE THREAD

**Issue by sirBertly** [ruby-openstack/ruby-openstack#45]
I'm not sure where to report this: when using the create_object container method, I get the above error

    container.create_object(content.name, {:metadata=>content.meta, :content_type=>content.mime_type}, File.open(cf, 'rb') {|file| file.read })

If I leave out the reading of the file, the object is created with 0 bytes
 
        container.create_object(content.name, {:metadata=>content.meta, :content_type=>content.mime_type})

stack trace:

    ArgumentError - wrong number of arguments (2 for 1):
    /Users/sirbertly/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/net/http/generic_request.rb:197:in `send_request_with_body_stream'
    /Users/sirbertly/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/net/http/generic_request.rb:132:in `exec'
    /Users/sirbertly/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/net/http.rb:1406:in `block in transport_request'
    /Users/sirbertly/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/net/http.rb:1405:in `transport_request'
    /Users/sirbertly/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/net/http.rb:1378:in `request'
    openstack (1.1.2) lib/openstack/connection.rb:132:in `put_object'
    openstack (1.1.2) lib/openstack/swift/storage_object.rb:252:in `write'
    openstack (1.1.2) lib/openstack/swift/storage_object.rb:58:in `create'
    openstack (1.1.2) lib/openstack/swift/container.rb:183:in `create_object'
    lib/kili_data_store.rb:34:in `block (2 levels) in write'

**Comment by f0086** [comment]
Duplicate. Fixed in `next`.
