### ISSUE TITLE
/openstack-1.1.2/lib/openstack/swift/connection.rb:171:in `read': wrong number of arguments (2 for 1) (ArgumentError)

### ISSUE THREAD

**Issue by GarfieldLinux** [ruby-openstack/ruby-openstack#46]
Hey ,
   code ---  swiftstorage.container("myfiles").create_object("file-from-ruby-api", {:metadata=>{"herpy"=>"derp"}, :content_type=>"text/plain"}, "this is the data from mem")

got error message --- /usr/local/rvm/gems/ruby-2.1.2/gems/openstack-1.1.2/lib/openstack/swift/connection.rb:171:in `read': wrong number of arguments (2 for 1) (ArgumentError)
	from /usr/local/rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/net/http/generic_request.rb:197:in `copy_stream'
	from /usr/local/rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/net/http/generic_request.rb:197:in `send_request_with_body_stream'
	from /usr/local/rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/net/http/generic_request.rb:132:in `exec'
	from /usr/local/rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/net/http.rb:1406:in `block in transport_request'
	from /usr/local/rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/net/http.rb:1405:in `catch'
	from /usr/local/rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/net/http.rb:1405:in `transport_request'
	from /usr/local/rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/net/http.rb:1378:in `request'
	from /usr/local/rvm/gems/ruby-2.1.2/gems/openstack-1.1.2/lib/openstack/connection.rb:132:in `put_object'
	from /usr/local/rvm/gems/ruby-2.1.2/gems/openstack-1.1.2/lib/openstack/swift/storage_object.rb:252:in `write'
	from /usr/local/rvm/gems/ruby-2.1.2/gems/openstack-1.1.2/lib/openstack/swift/storage_object.rb:58:in `create'
	from /usr/local/rvm/gems/ruby-2.1.2/gems/openstack-1.1.2/lib/openstack/swift/container.rb:183:in `create_object'
	from ruby-swift.rb:56:in `<class:SwiftStorage>'
	from ruby-swift.rb:7:in `<main>'

So  I tested ruby(1.8.7 1.9.3) is OK ,  But 2.0.0.2.1.2 show that error  message , Is there any update for ruby-openstack about new ruby version(2.0.0+) recently ?
Thanks  all .

**Comment by f0086** [comment]
Duplicate. Fixed in the `next`-Branch.
