### ISSUE TITLE
Bad URI when trying to connect to Openstack

### ISSUE THREAD

**Issue by Alex134** [ruby-openstack/ruby-openstack#53]
Hi, I'm trying to connect to a Openstack (Devstack) server with the line:
os = OpenStack::Connection.create({
    :username => "admin", 
    :auth_method => 'password',
    :api_key => "supersecret",
    :auth_url => "http://192.168.52.162/" })

And I got
>URI::InvalidURIError: bad URI(is not URI?): 
>    from /usr/lib/ruby/1.9.1/uri/common.rb:176:in 'split'
>    from /usr/lib/ruby/1.9.1/uri/common.rb:211:in 'parse'
>    from /usr/lib/ruby/1.9.1/uri/common.rb:747:in 'parse'
>    from /var/lib/gems/1.9.1/gems/openstack-1.1.2/lib/openstack/connection.rb:399:in 'initialize'
>    from /var/lib/gems/1.9.1/gems/openstack-1.1.2/lib/openstack/connection.rb:263:in 'new'
>    from /var/lib/gems/1.9.1/gems/openstack-1.1.2/lib/openstack/connection.rb:263:in 'init'
>    from /var/lib/gems/1.9.1/gems/openstack-1.1.2/lib/openstack/compute/connection.rb:12:in 'initialize'
>    from /var/lib/gems/1.9.1/gems/openstack-1.1.2/lib/openstack/connection.rb:66:in 'new'
>    from /var/lib/gems/1.9.1/gems/openstack-1.1.2/lib/openstack/connection.rb:66:in 'create'
>    from (irb):58
>    from /usr/bin/irb:12:in '<main>'

I think that is coming from the fact that there's no 'x-server-management-url' in the server http response and so the line:
> uri = URI.parse(response["x-server-management-url"])
send an uri error but I don't know how to fix it.

**Comment by bpieck** [comment]
Hm, all I can see, that this gem has choosen openstack API v1. Since API v2 should not use this header anymore, could this be the issue in your case?

**Comment by Alex134** [comment]
Yes, and it probably is. Where do you find that API v2 does use this header ? :)

**Comment by bpieck** [comment]
Oh, this gem guesses the version by checking, if auth_path matches /.*v2.0\/?$/. Since your auth_url does not have any path, I guess easiest way is to monkey patch it, via something like:

    class Authentication
      def init(conn)
        AuthV20.new(conn)
      end
    end
