### ISSUE TITLE
Support Identity v3

### ISSUE THREAD

**Issue by stenstad** [ruby-openstack/ruby-openstack#62]
Hi!

Since the release of Openstack Havana the preferred version of Identity to use is v3. Some cloud providers have now migrated to only supporting v3 for token generation to get support for domains.

Currently Ruby OpenStack does not work with providers that require support for Identity v3.

Would it be possible to add support for Identity v3 in this project as well?

**Comment by f0086** [comment]
Sure! This task need to be done.
Feel free to implement it and create a pull request if you need it ASAP.

**Comment by f0086** [comment]
I've implemented Identity v3 on a feature branch.
https://github.com/nitrado/ruby-openstack/tree/identity-v3

Can you please try it out and report any problems?
Use it as follows:

```
compute = OpenStack::Connection.create({
                                             username: '7a7700414cfc4910afd2a324e51d19d9',
                                             api_key: 'devstack',
                                             auth_method: 'password',
                                             auth_url: 'http://192.168.66.110:5000/v3',
                                             service_type: 'compute',
                                             authentenant_name: '63ef53e45c484272ac56c7db77996c1b',
                                             is_debug: true})
assert_true(compute.authok?)
compute.servers
    ...
```

```auth_method``` can be "password" or "token". The ```username``` has to be the user id, the ``authentant_name``` has to be the project id you want to access.

**Comment by stenstad** [comment]
Hi, I took a quick look at the code, and it seems the JSON is incomplete. Among other things the domain is missing.

Here is a valid JSON request to authenticate as user "mistertest" in domain "testdomain.com" with a password. We're here also asking to be scoped to the tenant "standard" in the domain "testdomain.com". I think you might be able to skip the tenant scope and be scoped to the default tenant for the user, but I'm not 100% sure.

Remember that a user in a domain can scope a token to a project in another domain as well. In OSC you have the environment variables OS_USER_DOMAIN_NAME (and _ID) to set domain the user belongs to, and OS_PROJECT_DOMAIN_NAME (and _ID) to set what domain the project you want to scope to belongs to.

```
{ "auth":{  
      "identity":{  
         "methods":[  
            "password"
         ],
         "password":{  
            "user":{  
               "name":"mistertest",
               "domain":{  
                  "name":"testdomain.com"
               },
               "password":"supersecret"
            }
         }
      },
      "scope":{  
         "project":{  
            "name":"standard",
            "domain":{  
               "name":"testdomain.com"
            }
         }
      }
   }
}
```

**Comment by mikaelhm** [comment]
I gave this a go: https://github.com/ruby-openstack/ruby-openstack/pull/85

**Comment by BirknerAlex** [comment]
FYI: I am currently reviewing the PR #85 of @mikaelhm. Should be going live soon as new release version.

**Comment by BirknerAlex** [comment]
The Identity v3 is already live since a few days in version v3.1.0.
