### ISSUE TITLE
Implement Keystone interaction?

### ISSUE THREAD

**Issue by ravenpi** [ruby-openstack/ruby-openstack#79]
I'd love to be able to create users and projects -- and associations between the two -- via this gem.  It could help with some of the scripting, etc., I'm trying to make happen.

**Comment by BirknerAlex** [comment]
Hey @ravenpi,

I would like to see this feature in our library. 👍 If you like to add this functionality please feel free. Just create a pull request, if everything works fine we will merge it. 

Regards,
Alexander

**Comment by Qwertyn** [comment]
Hello!
It can be made so
```ruby
keystone = OpenStack::Connection.create(username: 'admin', api_key: '123', auth_url: 'http://192.168.123.123:5000/v3/', authtenant_name: 'admin', service_type: 'identity', user_domain: 'default', project_name: 'admin', project_domain_name: 'default', endpoint_type: 'adminURL')

tenant = keystone.create_tenant(name: 'tenant1', description: 'description', enabled: true)

user = keystone.create_user(name: 'user1', password: 'password1', email: 'email@mail.ru')

role_id = keystone.roles.find { |r| r[:name] == 'Member' }[:id] # (Member, member, _member_, admin, ...)

keystone.add_user_to_tenant(tenant_id: tenant.id, role_id: role_id, user_id: user.id)
```
Methods Identity Connection v2 and v3: https://github.com/ruby-openstack/ruby-openstack/pull/87

**Comment by BirknerAlex** [comment]
Thanks again @Qwertyn :) 

Issue seems to be closable now.
