### ISSUE TITLE
2.0.2 Breaks `headerprep` in `lib/openstack/connection.rb:228`. 

### ISSUE THREAD

**Issue by mikaelhm** [ruby-openstack/ruby-openstack#80]
This commit: https://github.com/ruby-openstack/ruby-openstack/commit/44a421f0a87d37e3bd44d5b2b0f193eab69c4789

Deletes `lib/version.rb` which defined `OpenStack::VERSION`.

This is needed to set the user-agent header in connection.rb:228: https://github.com/ruby-openstack/ruby-openstack/blob/master/lib/openstack/connection.rb#L228

It looks like this commit changes the way versioning is defined, so I don' want to just add the file back in.

**Comment by BirknerAlex** [comment]
Hi @mikaelhm,

I will take a look into it. Thank for your report!

**Comment by BirknerAlex** [comment]
The issue has been fixed in the latest Github tag. Due some errors with jeweler a rubygems.org release is outstanding. Need to be fixed before.

But you can use the Github tag in your Gemfile.
