### ISSUE TITLE
ChunkedConnectionWrapper bug (and possible fix)

### ISSUE THREAD

**Issue by z5h** [ruby-openstack/ruby-openstack#84]
When I use vcr/webmock with ruby-openstack, I get an exception where webmock ends up calling `ChunkedConnectionWrapper.read` with 0 arguments (and `ChunkedConnectionWrapper.read` requires at least 1 argument).

As I trace the code, I see `ChunkedConnectionWrapper.read` defers to `StringIO.read` which accepts 0 arguments!

It seems, then, `ChunkedConnectionWrapper.read` should have method signature:
`def read(length=nil, buffer=nil)` instead of `def read(length, buffer=nil)`

Does this make sense?

**Comment by BirknerAlex** [comment]
The issue has been fixed in the latest version 3.3.3 by @bjorand.

The version is now live.
