### ISSUE TITLE
What are the options required? They're not listed out.

### ISSUE THREAD

**Issue by predatorian3** [ruby-openstack/ruby-openstack#95]
The OpenStack Volume Connection [#create_volume](https://github.com/ruby-openstack/ruby-openstack/blob/c0e4198e85b85bab6dfa83a9cd2ef8a962cfadfc/lib/openstack/volume/connection.rb#L25) method doesn't explicitly say what the options are that should be in the `options` hash. Is there anywhere where that options hash for volumes would be listed out?

**Comment by BirknerAlex** [comment]
Please take a look onto the official OpenStack documentation when using this library. All valid options depending on your OpenStack versions.

https://developer.openstack.org/api-ref/block-storage/v3/index.html#create-a-volume
